#!/bin/bash

client_id="4780f1b391a945f584286351b5d0a443"
client_secret="a1021e823dd74a6caa59b5df23b698cc"
redirect_uri="https://www.homedruon.com/callback"

browser="firefox-bin --new-window"
token_prefix="$HOME/.spoticli"

#################################################################

token_file="${token_prefix}/tokens"

if [ -e $token_file ]; then
    source $token_file
fi

#################################################################

test_token () {

    if [ $(($(date +%s)-$timestamp)) -gt 3000 ]
    then
        echo "Refreshing token ..."
        source spoticli_auth_refresh
    fi

}

