#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
source $SCRIPTPATH/config

test_token

curl -s -S -X "PUT" "https://api.spotify.com/v1/me/player" \
    -H "Content-Type: application/json" \
    -H "Accept: application/json" \
    -H "Authorization: Bearer $access_token" \
    --data "{\"device_ids\":[\"$1\"]}"
