#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
source $SCRIPTPATH/config

test_token

curl -s -S -X "GET" "https://api.spotify.com/v1/search?q=$1&type=track" \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $access_token" \
    -H "Content-Length: 0"
