#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
source $SCRIPTPATH/spoticli_common

source $token_file

token_response=$(curl --silent --show-error \
    --data grant_type=refresh_token \
    --data client_id=${client_id} \
    --data client_secret=${client_secret}\
    --data refresh_token=${refresh_token} \
    ${spotify_auth}/api/token)

#echo $token_response
error=$(echo $token_response | jq -r .error)

if [[ $error != "null" ]]; then
    echo "Error while refreshing access token:" >&2
    echo " server returned: $error" >&2
    exit -1
fi

access_token=$(echo $token_response | jq --raw-output .access_token)
timestamp="$(date +%s)"

echo "#!/bin/bash" > $token_file
echo "timestamp=${timestamp}" >> $token_file
echo "access_token=$access_token" >> $token_file
echo "refresh_token=$refresh_token" >> $token_file
