#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
source $SCRIPTPATH/config

source $token_file

token_response="$(curl -s -S \
    -d grant_type=refresh_token \
    -d client_id=${client_id} \
    -d client_secret=${client_secret}\
    -d refresh_token=${refresh_token} \
    https://accounts.spotify.com/api/token)"

# echo $token_response

access_token="$(echo $token_response | cut -d "," -f 1 | cut -d ":" -f 2 | sed -e 's/\"//g' )"
timestamp="$(date +%s)"

echo "#!/bin/bash" > $token_file
echo "timestamp=${timestamp}" >> $token_file
echo "access_token=$access_token" >> $token_file
echo "refresh_token=$refresh_token" >> $token_file

